/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    id("com.vanniktech.maven.publish") version "0.33.0"
    id("de.undercouch.download") version "5.7.0"
    id("signing")
}

group = "io.kestra.libs"
description = "Kestra lib for AI Copilot-related services"

dependencies {
    compileOnly(libs.jakarta.validation)
    compileOnly(libs.langchain4j)
    compileOnly(libs.jackson.databind)
    compileOnly(libs.jackson.yaml)

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.assertj)
    testImplementation(libs.mockito.junit.jupiter)
    testImplementation(libs.jakarta.validation)
    testImplementation(libs.langchain4j)
    testImplementation(libs.langchain4j.google.ai.gemini)
    testImplementation(libs.jackson.databind)
    testImplementation(libs.jackson.yaml)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 21
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// maven publish
val isBuildSnapshot = version.toString().endsWith("-SNAPSHOT")
repositories {
    mavenLocal()
    mavenCentral()
    if (isBuildSnapshot) {
        maven { url = uri("https://central.sonatype.com/repository/maven-snapshots/") }
    }
}
mavenPublishing {
    publishToMavenCentral()
    signAllPublications()
    coordinates("${project.group}", "${project.name}", "${project.version}")

    pom {
        name.set(project.name)
        description.set("${project.group}:${project.name}:${rootProject.version}")
        url.set("https://github.com/kestra-io/${rootProject.name}")

        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                id.set("tchiotludo")
                name.set("Ludovic Dehon")
                email.set("ldehon@kestra.io")
            }
        }
        scm {
            connection.set("scm:git:")
            url.set("https://github.com/kestra-io/${rootProject.name}")
        }
    }
}
tasks.named<org.gradle.jvm.tasks.Jar>("jar") {
    manifest {
        attributes(
            mapOf(
                "X-Kestra-Name" to project.name,
                "X-Kestra-Title" to "Kestra libs-copilot",
                "X-Kestra-Group" to project.group,
                "X-Kestra-Description" to (project.description),
                "X-Kestra-Version" to project.version
            )
        )
    }
}

// release
val autotagBinDir = layout.buildDirectory.dir("tools")
val autotagBinary = autotagBinDir.map { it.file("autotag") }
tasks.register<Exec>("installAutotag") {
    outputs.file(autotagBinary)
    commandLine(
        "sh", "-c",
        "curl -sL https://git.io/autotag-install | sh -s -- -b \"${autotagBinDir.get().asFile.absolutePath}\""
    )
}
tasks.register<Exec>("calculateNextSemverVersion") {
    dependsOn("installAutotag")
    commandLine(autotagBinary.get().asFile.absolutePath, "-ne", "--scheme=conventional")
}

tasks.register("releaseVersion") {
    notCompatibleWithConfigurationCache("Runs git and edits build file")
    doLast {
        val rawVersion = (findProperty("versionToRelease") as? String)?.trim().orEmpty()
        if (rawVersion.isEmpty()) {
            throw GradleException("Missing -PversionToRelease=... value")
        }
        if (rawVersion.isEmpty()) {
            throw GradleException("calculateNextSemverVersion produced no version output")
        }

        val gradleVersion = rawVersion.removePrefix("v")
        setVersionInProperties(rawVersion)

        val tagName = if (rawVersion.startsWith("v")) rawVersion else "v$rawVersion"
        fun runGit(vararg args: String) {
            val process = ProcessBuilder(listOf("git") + args)
                .directory(rootProject.projectDir)
                .inheritIO()
                .start()
            val exitCode = process.waitFor()
            if (exitCode != 0) {
                throw GradleException("git ${args.joinToString(" ")} failed with exit code $exitCode")
            }
        }
        runGit("add", rootProject.file("gradle.properties").absolutePath)
        runGit("commit", "-m", "chore(version): release $gradleVersion")
        runGit("tag", tagName)
        runGit("push", "origin", tagName)
    }
}

fun setVersionInProperties(rawVersion: String) {
    val newVersion = rawVersion.removePrefix("v").trim().trim('"')
    val propertiesFile = rootProject.file("gradle.properties")
    val current = propertiesFile.readText()
    val versionRegex = Regex("(?m)^version\\s*=\\s*[^\\n]+\\s*$")
    val updated = if (versionRegex.containsMatchIn(current)) {
        current.replace(versionRegex, "version=$newVersion")
    } else {
        (current.trimEnd() + "\nversion=$newVersion\n")
    }
    if (updated != current) {
        propertiesFile.writeText(updated)
    }
}
