import de.undercouch.gradle.tasks.download.Download
import org.gradle.api.GradleException

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.google.cloud.artifactregistry.gradle-plugin") version "2.2.5"
    id("de.undercouch.download") version "5.7.0"
}


version = "0.0.2"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// release
val autotagBinDir = layout.buildDirectory.dir("tools")
val autotagBinary = autotagBinDir.map { it.file("autotag") }
val nextVersionFile = layout.buildDirectory.file("next-version.txt")
tasks.register<Exec>("installAutotag") {
    outputs.file(autotagBinary)
    commandLine(
        "sh", "-c",
        "curl -sL https://git.io/autotag-install | sh -s -- -b \"${autotagBinDir.get().asFile.absolutePath}\""
    )
}
tasks.register<Exec>("calculateNextSemverVersion") {
    dependsOn("installAutotag")
    notCompatibleWithConfigurationCache("Writes tool output to file at execution time")
    outputs.file(nextVersionFile)
    doFirst {
        nextVersionFile.get().asFile.parentFile.mkdirs()
        standardOutput = nextVersionFile.get().asFile.outputStream()
    }
    commandLine(autotagBinary.get().asFile.absolutePath, "-ne", "--scheme=conventional", "--repo=../")
}

tasks.register("releaseNextVersion") {
    dependsOn("calculateNextSemverVersion")
    notCompatibleWithConfigurationCache("Runs git and edits build file")
    doLast {
        val rawVersion = nextVersionFile.get().asFile.readText().trim()
        if (rawVersion.isEmpty()) {
            throw GradleException("calculateNextSemverVersion produced no version output")
        }

        val gradleVersion = rawVersion.removePrefix("v")
        val buildFile = project.buildFile
        val current = buildFile.readText()
        val versionRegex = Regex("(?m)^version\\s*=\\s*\"[^\"]+\"\\s*$")
        val updated = if (versionRegex.containsMatchIn(current)) {
            current.replace(versionRegex, "version = \"$gradleVersion\"")
        } else {
            val pluginsRegex = Regex("(?s)plugins\\s*\\{.*?\\}\\s*")
            val match = pluginsRegex.find(current)
            if (match != null) {
                val insertAt = match.range.last + 1
                current.substring(0, insertAt) + "\nversion = \"$gradleVersion\"\n\n" + current.substring(insertAt)
            } else {
                "version = \"$gradleVersion\"\n\n" + current
            }
        }
        if (updated != current) {
            buildFile.writeText(updated)
        }

        val tagName = if (rawVersion.startsWith("v")) rawVersion else "v$rawVersion"
        fun runGit(vararg args: String) {
            val process = ProcessBuilder(listOf("git") + args)
                .directory(rootProject.projectDir)
                .inheritIO()
                .start()
            val exitCode = process.waitFor()
            if (exitCode != 0) {
                throw GradleException("git ${args.joinToString(" ")} failed with exit code $exitCode")
            }
        }
        runGit("add", buildFile.absolutePath)
        runGit("commit", "-m", "Bump lib version to $gradleVersion")
        runGit("tag", tagName)
    }
}

// maven publish
val isBuildSnapshot = version.toString().endsWith("-SNAPSHOT")
repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri("artifactregistry://europe-west1-maven.pkg.dev/kestra-host/maven") }
    if (isBuildSnapshot) {
        maven { url = uri("https://central.sonatype.com/repository/maven-snapshots/") }
        maven { url = uri("artifactregistry://europe-west1-maven.pkg.dev/kestra-host/maven-snapshot") }
    }
}

/*
publishing {
    repositories {
        maven {
            url = uri(
                if (isBuildSnapshot) {
                    "artifactregistry://europe-west1-maven.pkg.dev/kestra-host/maven-snapshot"
                } else {
                    "artifactregistry://europe-west1-maven.pkg.dev/kestra-host/maven"
                }
            )
        }
    }
}*/
