import de.undercouch.gradle.tasks.download.Download
import org.gradle.api.GradleException

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.google.cloud.artifactregistry.gradle-plugin") version "2.2.5"
    id("de.undercouch.download") version "5.7.0"
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// release
val autotagBinDir = layout.buildDirectory.dir("tools")
val autotagBinary = autotagBinDir.map { it.file("autotag") }
tasks.register<Exec>("installAutotag") {
    outputs.file(autotagBinary)
    commandLine(
        "sh", "-c",
        "curl -sL https://git.io/autotag-install | sh -s -- -b \"${autotagBinDir.get().asFile.absolutePath}\""
    )
}
tasks.register<Exec>("calculateNextSemverVersion") {
    dependsOn("installAutotag")
    commandLine(autotagBinary.get().asFile.absolutePath, "-ne", "--scheme=conventional", "--repo=../")
}

tasks.register("releaseVersion") {
    notCompatibleWithConfigurationCache("Runs git and edits build file")
    doLast {
        val rawVersion = (findProperty("versionToRelease") as? String)?.trim().orEmpty()
        if (rawVersion.isEmpty()) {
            throw GradleException("Missing -PversionToRelease=... value")
        }
        if (rawVersion.isEmpty()) {
            throw GradleException("calculateNextSemverVersion produced no version output")
        }

        val gradleVersion = rawVersion.removePrefix("v")
        setVersionInProperties(rawVersion)

        val tagName = if (rawVersion.startsWith("v")) rawVersion else "v$rawVersion"
        fun runGit(vararg args: String) {
            val process = ProcessBuilder(listOf("git") + args)
                .directory(rootProject.projectDir)
                .inheritIO()
                .start()
            val exitCode = process.waitFor()
            if (exitCode != 0) {
                throw GradleException("git ${args.joinToString(" ")} failed with exit code $exitCode")
            }
        }
        runGit("add", rootProject.file("gradle.properties").absolutePath)
        runGit("commit", "-m", "chore(version): release $gradleVersion")
        runGit("tag", tagName)
    }
}

fun setVersionInProperties(rawVersion: String) {
    val newVersion = rawVersion.removePrefix("v")
    val propertiesFile = rootProject.file("gradle.properties")
    val current = propertiesFile.readText()
    val versionRegex = Regex("(?m)^version\\s*=\\s*\"?[^\"\\n]+\"?\\s*$")
    val updated = if (versionRegex.containsMatchIn(current)) {
        current.replace(versionRegex, "version = \"$newVersion\"")
    } else {
        (current.trimEnd() + "\nversion = \"$newVersion\"\n")
    }
    if (updated != current) {
        propertiesFile.writeText(updated)
    }
}

// maven publish
val isBuildSnapshot = version.toString().endsWith("-SNAPSHOT")
repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri("artifactregistry://europe-west1-maven.pkg.dev/kestra-host/maven") }
    if (isBuildSnapshot) {
        maven { url = uri("https://central.sonatype.com/repository/maven-snapshots/") }
        maven { url = uri("artifactregistry://europe-west1-maven.pkg.dev/kestra-host/maven-snapshot") }
    }
}

/*
publishing {
    repositories {
        maven {
            url = uri(
                if (isBuildSnapshot) {
                    "artifactregistry://europe-west1-maven.pkg.dev/kestra-host/maven-snapshot"
                } else {
                    "artifactregistry://europe-west1-maven.pkg.dev/kestra-host/maven"
                }
            )
        }
    }
}*/
