name: Auto Release
# when a semver commit worthy of being release reach the main branch, increment semver version and release it automatically
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
permissions:
  contents: write
  actions: read
  pull-requests: write
  packages: read


jobs:
  tag:
    if: ${{ github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, 'chore(release)') && !contains(github.event.head_commit.message, 'chore(version)') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: kestra-io/actions/composite/checkout-and-auth@main
        with:
          gh-app-id: ${{ secrets.GH_BOT_APP_ID }}
          gh-app-private-key: ${{ secrets.GH_BOT_PRIVATE_KEY }}
          fetch-depth: 0
      - name: Git - Configure
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: setup Java
        uses: kestra-io/actions/composite/setup-build@main
        with:
          java-enabled: 'true'
          java-version: '25'

      - name: Build with Gradle
        env:
          GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
        run: |
          ./gradlew check

      - name: calculate next semver
        id: calculate-next-semver
        run: |
          VERSION=$(./gradlew -q calculateNextSemverVersion)
          echo "version to release: ${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Auto release
        run: |
          ./gradlew releaseVersion -PversionToRelease=${{ steps.calculate-next-semver.outputs.version }}
